"""
Django settings for xx project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

from decouple import AutoConfig, Config, Csv, RepositoryEnv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Anchor python-decouple to the .env beside the project root instead of letting
# AutoConfig discover one relative to the ambient cwd / entrypoint. OS environment
# variables still take precedence (Config checks os.environ before the file), so
# prod / CI that inject real env vars are unchanged. Falls back to AutoConfig when
# no .env file exists (pure-env containers / CI). See .env.example for the keys.
_ENV_FILE = BASE_DIR / ".env"
if _ENV_FILE.is_file():
    config = Config(RepositoryEnv(str(_ENV_FILE)))
else:
    config = AutoConfig()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-r8^--b8z3)vvs=eonw90b=u+(#jgyy4%f6vt#@zn@ww@#v30s1",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    'django_filters',

    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',

    # OAuth 2.1 authorization server backing the MCP endpoint (see mcp_server/).
    'oauth2_provider',

    'corsheaders',

    'tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'organizer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'organizer.wsgi.application'
# ASGI entrypoint (uvicorn organizer.asgi:application). Required to serve the MCP
# Streamable HTTP endpoint at /mcp; the plain REST API still runs fine under WSGI.
ASGI_APPLICATION = 'organizer.asgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

# AUTH_USER_MODEL = "user.OrganizerUser"
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Per-worktree test-database plumbing (see bin/wt). Both keys default to Django's
# standard behavior, so prod and the main checkout are unchanged (neither sets them):
#   DB_TEST_NAME     — explicit test DB name (default: test_<DB_NAME>). bin/wt writes
#                      test_<worktree_db> into each worktree's .env, keeping the
#                      test-DB name explicit and unique per worktree.
#   TEST_DB_TEMPLATE — a prebuilt Postgres template DB to clone the test DB from
#                      instead of replaying every migration on cold build. Left unset
#                      unless the template exists (Django's PG backend would fail
#                      CREATE … WITH TEMPLATE on a missing name); `bin/wt template
#                      refresh` builds it and `bin/wt new` auto-sets this in a
#                      worktree's .env when it's present.
_DB_NAME = config("DB_NAME", default="organizer")
_TEST_DB_TEMPLATE = config("TEST_DB_TEMPLATE", default="")

_test_config = {"NAME": config("DB_TEST_NAME", default=f"test_{_DB_NAME}")}
if _TEST_DB_TEMPLATE:
    _test_config["TEMPLATE"] = _TEST_DB_TEMPLATE

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _DB_NAME,
        'USER': config("DB_USER", default="organizer"),
        'PASSWORD': config("DB_PASSWORD", default=""),
        'HOST': config("DB_HOST", default="127.0.0.1"),
        'PORT': config("DB_PORT", default=5432, cast=int),
        'TEST': _test_config,
    }
}


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static"

STATICFILES_DIRS = (
    ("css", BASE_DIR / "static" / "css"),
    ("js", BASE_DIR / "static" / "js"),
    ("templates", BASE_DIR / "static" / "templates")
)

RECAPTCHA_PUBLIC_KEY = ""
RECAPTCHA_PRIVATE_KEY = ""
GOOGLE_API_KEY = ""

SITE_ID = 1
# The OAuth authorize view (django-oauth-toolkit) redirects unauthenticated users here
# with a ?next= back to the consent screen; the admin login honours ?next=.
LOGIN_URL = "/admin/login/"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        # 'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    )
}

REST_AUTH = {
    "TOKEN_SERIALIZER": "tasks.api.serializers.UserTokenSerializer",
}

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:4200",
    cast=Csv(),
)


# python-decouple keeps everything after `=` as the value (including any trailing `# comment`),
# so sanitize before casting — this tolerates a stray inline comment or whitespace in a hand-edited
# .env instead of crashing on import (e.g. `RECURRING_TASKS_HOUR=6  # 6am`).
def _strip_inline_comment(value):
    return str(value).split("#", 1)[0].strip()


def _env_int(key, default):
    return config(key, default=default, cast=lambda v: int(_strip_inline_comment(v)))


# Celery — drives recurring-task generation via celery beat. The broker is Redis by default.
# The REST API does not require Celery; only automatic task generation depends on it. Generation can
# always be run manually with `manage.py generate_recurring_tasks` if the broker is unavailable.
from celery.schedules import crontab  # noqa: E402

CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="")
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULE = {
    "generate-recurring-tasks": {
        "task": "tasks.generate_recurring_tasks",
        # Daily at a configurable hour (local CELERY_TIMEZONE). Sanitized so a stray inline comment
        # in .env (e.g. `RECURRING_TASKS_HOUR=6  # 6am`) doesn't crash the worker/beat on startup.
        "schedule": crontab(minute=0, hour=_env_int("RECURRING_TASKS_HOUR", 6)),
    },
}


# --- MCP server + OAuth 2.1 authorization server -----------------------------------------
# (_strip_inline_comment / _env_int are defined above, near the Celery config — they tolerate a
# stray inline comment in a hand-edited .env, e.g. `OAUTH_ACCESS_TOKEN_TTL=28800  # 8h`.)

# Public, externally-reachable base URL of this deployment. It anchors the OAuth issuer and
# the MCP resource identifier advertised in discovery metadata, so it MUST match the URL the
# MCP client connects to (e.g. https://organizer.example.com). Defaults to the dev server.
MCP_BASE_URL = _strip_inline_comment(config("MCP_BASE_URL", default="http://localhost:8000")).rstrip("/")

# django-oauth-toolkit: authorization-code + PKCE, read/write scopes. Access tokens are opaque
# and introspected in-process by the MCP TokenVerifier (mcp_server/auth.py) — no JWTs/JWKS.
OAUTH2_PROVIDER = {
    "SCOPES": {
        "read": "Read your tasks, projects, tags, and comments",
        "write": "Create, update, and delete your tasks, projects, tags, and comments",
    },
    "DEFAULT_SCOPES": ["read", "write"],
    "PKCE_REQUIRED": True,
    "ACCESS_TOKEN_EXPIRE_SECONDS": _env_int("OAUTH_ACCESS_TOKEN_TTL", 60 * 60 * 8),
    "REFRESH_TOKEN_EXPIRE_SECONDS": _env_int("OAUTH_REFRESH_TOKEN_TTL", 60 * 60 * 24 * 30),
    "ROTATE_REFRESH_TOKEN": True,
    # Allow http redirect URIs so loopback MCP clients (Claude Desktop / Claude Code / mcp-remote)
    # work in addition to https web connectors.
    "ALLOWED_REDIRECT_URI_SCHEMES": ["https", "http"],
}


