# Generated by Django 6.0.6 on 2026-06-07 22:09

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20220220_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='completed_date',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='completed', null=True, when={True}),
        ),
    ]
