# Generated by Django 6.0.6 on 2026-07-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskitem_completed_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskitem',
            options={'ordering': ['order', '-priority', '-start_date', '-changed_date', '-created_date', 'pk']},
        ),
    ]
