# Generated by Django 6.0.6 on 2026-07-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_taskcomment_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskitem',
            options={'ordering': ['-changed_date', '-pk']},
        ),
    ]
