# Generated by Django 6.0.6 on 2026-07-03 20:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tag_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(4, 'Prioritară'), (2, 'Neutră'), (1, 'Joasă')], default=2)),
                ('estimated_time', models.IntegerField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Zilnic'), ('weekly', 'Săptămânal'), ('monthly', 'Lunar'), ('yearly', 'Anual')], default='monthly', max_length=16)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True)),
                ('month_of_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_on', models.DateField(blank=True, null=True)),
                ('end_on', models.DateField(blank=True, null=True)),
                ('rrule', models.TextField(blank=True, null=True)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('skip_if_previous_open', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated_occurrence', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates', to='tasks.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='task_templates', to='tasks.tag')),
            ],
            options={
                'ordering': ['-changed_date', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='taskitem',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='tasks.tasktemplate'),
        ),
    ]
