"""Migrate the legacy 2017 ``organize_*`` schema into the current ``tasks_*`` schema.

Production historically ran the original ``organize`` Django app. Its data model is nearly
identical to the current ``tasks`` app — the only schema addition is ``TaskItem.for_today`` (and a
nullable ``completed_date``); ``owner`` is still ``auth.User``. This command moves a production
``pg_dump`` (custom format) into the current schema by restoring just the legacy tables into the
target database and copying them across with an explicit column mapping.

Usage::

    uv run python manage.py migrate_legacy /path/to/organizer.dump

Run it against a **freshly migrated** database (``manage.py migrate`` first). See
``docs/data-migration.md`` for the full runbook.
"""

import os
import shutil
import subprocess

from django.core.management.base import BaseCommand, CommandError
from django.db import connection, transaction

# Legacy domain tables to restore (definition + data) from the dump.
LEGACY_TABLES = [
    "organize_tag",
    "organize_project",
    "organize_project_tags",
    "organize_taskitem",
    "organize_taskitem_tags",
    "organize_taskcomment",
]

# Identity tables to restore data-only into the freshly-migrated auth tables. Order is FK-safe.
# Permissions / content types / per-user-or-group permissions are intentionally skipped: they are
# regenerated by ``migrate`` and their ids do not line up across schemas.
AUTH_TABLES = ["auth_group", "auth_user", "auth_user_groups", "authtoken_token"]

# (target, source, columns, extra_select) — copy in this FK-safe order.
# ``extra_select`` appends literal/derived columns not present in the source.
COPY_PLAN = [
    ("tasks_tag", "organize_tag", ["id", "name", "slug", "description", "color"], []),
    (
        "tasks_project",
        "organize_project",
        ["id", "title", "description", "slug", "start_date", "end_date"],
        [],
    ),
    ("tasks_project_tags", "organize_project_tags", ["id", "project_id", "tag_id"], []),
    (
        "tasks_taskitem",
        "organize_taskitem",
        [
            "id", "title", "description", "start_date", "end_date", "completed_date",
            "estimated_time", '"order"', "created_date", "changed_date", "status", "completed",
            "priority", "owner_id", "parent_task_id", "project_id",
        ],
        [("for_today", "false")],  # column added in the new schema
    ),
    ("tasks_taskitem_tags", "organize_taskitem_tags", ["id", "taskitem_id", "tag_id"], []),
    (
        "tasks_taskcomment",
        "organize_taskcomment",
        ["id", "timestamp", "description", "task_id", "user_id"],
        [],
    ),
]

# Tables whose id sequence must be re-synced after copying rows with explicit ids.
RESEQUENCE_TABLES = [
    "auth_group", "auth_user", "tasks_tag", "tasks_project", "tasks_project_tags",
    "tasks_taskitem", "tasks_taskitem_tags", "tasks_taskcomment",
]


class Command(BaseCommand):
    help = "Migrate a legacy organize_* pg_dump into the current tasks_* schema."

    def add_arguments(self, parser):
        parser.add_argument("dump_path", help="Path to the production pg_dump (custom format).")
        parser.add_argument(
            "--force",
            action="store_true",
            help="Proceed even if the target tasks_taskitem table already has rows.",
        )
        parser.add_argument(
            "--skip-auth",
            action="store_true",
            help="Do not import users/groups/tokens (use when the target already has the users).",
        )
        parser.add_argument(
            "--keep-temp",
            action="store_true",
            help="Keep the restored organize_* tables instead of dropping them at the end.",
        )

    def handle(self, *args, **options):
        dump_path = os.path.abspath(options["dump_path"])
        if not os.path.exists(dump_path):
            raise CommandError(f"Dump file not found: {dump_path}")
        if shutil.which("pg_restore") is None:
            raise CommandError("pg_restore not found on PATH (install the postgresql client tools).")

        db = connection.settings_dict
        if "postgresql" not in db["ENGINE"]:
            raise CommandError("This command only supports PostgreSQL targets.")

        self._require_migrated_schema()
        self._guard_existing_data(force=options["force"])

        self.stdout.write(self.style.MIGRATE_HEADING("1/5 Restoring legacy tables from dump…"))
        self._pg_restore(dump_path, LEGACY_TABLES, data_only=False)

        if options["skip_auth"]:
            self.stdout.write("2/5 Skipping auth/identity import (--skip-auth).")
        else:
            self.stdout.write(self.style.MIGRATE_HEADING("2/5 Restoring users/groups/tokens…"))
            self._pg_restore(dump_path, AUTH_TABLES, data_only=True)

        self.stdout.write(self.style.MIGRATE_HEADING("3/5 Copying domain data into tasks_* …"))
        copied = self._copy_data()

        self.stdout.write(self.style.MIGRATE_HEADING("4/5 Re-syncing id sequences…"))
        self._resequence()

        if options["keep_temp"]:
            self.stdout.write("5/5 Keeping organize_* tables (--keep-temp).")
        else:
            self.stdout.write(self.style.MIGRATE_HEADING("5/5 Dropping temporary organize_* tables…"))
            self._drop_legacy_tables()

        self.stdout.write(self.style.SUCCESS("\nMigration complete. Rows copied:"))
        for table, count in copied.items():
            self.stdout.write(f"  {table:<24} {count}")

    # --- steps -------------------------------------------------------------------------------

    def _require_migrated_schema(self):
        with connection.cursor() as cur:
            cur.execute("SELECT to_regclass('public.tasks_taskitem');")
            if cur.fetchone()[0] is None:
                raise CommandError(
                    "Target schema not found (tasks_taskitem missing). Run "
                    "'manage.py migrate' against this database first."
                )

    def _guard_existing_data(self, force):
        with connection.cursor() as cur:
            cur.execute("SELECT count(*) FROM tasks_taskitem;")
            existing = cur.fetchone()[0]
        if existing and not force:
            raise CommandError(
                f"tasks_taskitem already has {existing} rows. Refusing to import into a "
                "non-empty schema. Re-run with --force if you really mean to."
            )

    def _pg_restore(self, dump_path, tables, data_only):
        db = connection.settings_dict
        cmd = [
            "pg_restore", "--no-owner", "--no-privileges",
            "-h", db.get("HOST") or "localhost",
            "-p", str(db.get("PORT") or "5432"),
            "-U", db["USER"],
            "-d", db["NAME"],
        ]
        if data_only:
            cmd += ["--data-only", "--disable-triggers"]
        for table in tables:
            cmd += ["-t", table]
        cmd.append(dump_path)

        env = os.environ.copy()
        if db.get("PASSWORD"):
            env["PGPASSWORD"] = db["PASSWORD"]
        result = subprocess.run(cmd, env=env, capture_output=True, text=True)
        # pg_restore is noisy; only fail on a non-zero exit.
        if result.returncode != 0:
            raise CommandError(
                f"pg_restore failed (exit {result.returncode}):\n{result.stderr.strip()}"
            )

    def _copy_data(self):
        copied = {}
        with transaction.atomic():
            with connection.cursor() as cur:
                # Superuser-only: bypass FK/triggers so insertion order and self-FKs don't matter.
                cur.execute("SET session_replication_role = replica;")
                try:
                    for target, source, columns, extra in COPY_PLAN:
                        target_cols = columns + [name for name, _ in extra]
                        select_cols = columns + [literal for _, literal in extra]
                        cur.execute(
                            f"INSERT INTO {target} ({', '.join(target_cols)}) "
                            f"SELECT {', '.join(select_cols)} FROM {source};"
                        )
                        copied[target] = cur.rowcount
                finally:
                    cur.execute("SET session_replication_role = DEFAULT;")
        return copied

    def _resequence(self):
        with connection.cursor() as cur:
            for table in RESEQUENCE_TABLES:
                cur.execute(
                    "SELECT setval("
                    "  pg_get_serial_sequence(%s, 'id'),"
                    "  COALESCE((SELECT MAX(id) FROM " + table + "), 1),"
                    "  (SELECT MAX(id) IS NOT NULL FROM " + table + ")"
                    ");",
                    [table],
                )

    def _drop_legacy_tables(self):
        with connection.cursor() as cur:
            for table in reversed(LEGACY_TABLES):
                cur.execute(f"DROP TABLE IF EXISTS {table} CASCADE;")
