# Generated by Django 6.0.7 on 2026-10-05 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0009_tasktemplate_taskitem_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunHubOAuthClient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_url", models.URLField(max_length=512)),
                ("redirect_uri", models.URLField(max_length=1024)),
                ("client_id", models.CharField(max_length=255)),
                ("scope", models.CharField(blank=True, default="", max_length=255)),
                ("authorization_endpoint", models.URLField(max_length=1024)),
                ("token_endpoint", models.URLField(max_length=1024)),
                ("revocation_endpoint", models.URLField(blank=True, default="", max_length=1024)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "VolunHub OAuth client",
                "verbose_name_plural": "VolunHub OAuth clients",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("base_url", "redirect_uri"), name="unique_volunhub_client_per_redirect"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VolunHubConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("access_token_encrypted", models.TextField(blank=True, default="")),
                ("refresh_token_encrypted", models.TextField(blank=True, default="")),
                ("access_token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("granted_scope", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("needs_reauth", "Needs re-authorization")],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("content_push_enabled", models.BooleanField(default=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunhub_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connections",
                        to="volunhub.volunhuboauthclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "VolunHub connection",
                "verbose_name_plural": "VolunHub connections",
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunHubOAuthFlow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(max_length=128, unique=True)),
                ("code_verifier", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows",
                        to="volunhub.volunhuboauthclient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunhub_oauth_flows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "VolunHub OAuth flow",
                "verbose_name_plural": "VolunHub OAuth flows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunHubProjectLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.BigIntegerField(unique=True)),
                ("external_slug", models.CharField(blank=True, default="", max_length=255)),
                ("external_name", models.CharField(blank=True, default="", max_length=1024)),
                ("auto_created", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="volunhub_links",
                        to="tasks.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "VolunHub project link",
                "verbose_name_plural": "VolunHub project links",
                "ordering": ["external_name"],
            },
        ),
        migrations.CreateModel(
            name="VolunHubTaskLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.BigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Synced"), ("removed", "Removed from VolunHub")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "removed_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unassigned", "Unassigned in VolunHub"),
                            ("deleted", "Deleted in VolunHub"),
                            ("disconnected", "VolunHub disconnected"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("external_project_id", models.BigIntegerField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="volunhub_link",
                        to="tasks.taskitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunhub_task_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "VolunHub task link",
                "verbose_name_plural": "VolunHub task links",
                "indexes": [models.Index(fields=["user", "state"], name="volunhub_vo_user_id_e4a22a_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "external_id"), name="unique_volunhub_task_per_user")
                ],
            },
        ),
    ]
