# Generated by Django 6.0.7 on 2026-08-24 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0009_tasktemplate_taskitem_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("access_token_encrypted", models.TextField(blank=True, default="")),
                ("refresh_token_encrypted", models.TextField(blank=True, default="")),
                ("bot_id", models.CharField(blank=True, default="", max_length=64)),
                ("workspace_id", models.CharField(blank=True, default="", max_length=64)),
                ("workspace_name", models.CharField(blank=True, default="", max_length=255)),
                ("workspace_icon", models.CharField(blank=True, default="", max_length=1024)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("unprovisioned", "No database yet"),
                            ("needs_reauth", "Needs re-authorization"),
                            ("schema_drift", "Schema changed in Notion"),
                        ],
                        default="unprovisioned",
                        max_length=32,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_full_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notion connection",
                "verbose_name_plural": "Notion connections",
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="NotionDatabase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("database_id", models.CharField(max_length=64)),
                ("data_source_id", models.CharField(max_length=64)),
                ("parent_page_id", models.CharField(max_length=64)),
                ("property_ids", models.JSONField(blank=True, default=dict)),
                ("pull_watermark", models.DateTimeField(blank=True, null=True)),
                (
                    "bootstrap_state",
                    models.CharField(
                        choices=[("pending", "Pending"), ("running", "Uploading existing tasks"), ("done", "Done")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("bootstrap_cursor", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="database",
                        to="notion.notionconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notion database",
                "verbose_name_plural": "Notion databases",
            },
        ),
        migrations.CreateModel(
            name="NotionOAuthFlow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_oauth_flows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notion OAuth flow",
                "verbose_name_plural": "Notion OAuth flows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotionTaskLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notion_page_id", models.CharField(max_length=64)),
                ("notion_last_edited_time", models.DateTimeField(blank=True, null=True)),
                ("local_changed_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="links", to="notion.notiondatabase"
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notion_link",
                        to="tasks.taskitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notion task link",
                "verbose_name_plural": "Notion task links",
                "indexes": [models.Index(fields=["database", "task"], name="notion_noti_databas_235a58_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("database", "notion_page_id"), name="unique_notion_page_per_database"
                    )
                ],
            },
        ),
    ]
